version: '3'

services:
  personal-website:
    image: kiritchoukc/personal
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: www.kiritchoukc.com
    container_name: personal_website
networks:
  default:
    external:
      name: nginx-proxy
